config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :events
  resources :attendances, only: [:create], as: 'join_events'
  resources :attendances, only: [:destroy], as: 'leave_event'
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances
  has_many :attendee, through: :attendances, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :events, inverse_of: 'creator'
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    event_id = params[:event_id]
    @attendance = current_user.attendances.new(event_id: event_id)
    if Attendance.where.not(["event_id = ?", event_id]).present?
      flash[:notice] = "You've already joined this event."
      redirect_to root_path
    elsif @attendance.save
      flash[:notice] = 'Event added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to create event!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      flash[:notice] = 'Event added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to create event!'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%=form_with model: event do |form| %>
 <ul>
  <% event.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div>
    <%=form.label :title, "Title:" %><br>
    <%=form.text_field :title%>
  </div>
  <div>
    <%=form.label :description, "Description:" %><br>
    <%=form.text_area :description, size: "70x5" %>
  </div>
  <div>
    <%=form.submit %>
  </div>
<%end%>

app/views/events/index.html.erb
<h1>Events</h1>

<ul>
  <% @event.each do |event| %>
    <li>
      <%= link_to event.title, event %>
    </li>
  <% end %>
</ul>

<%= link_to "New Event", new_event_path %> <br>
<%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }  %> <br>
<%= link_to "Sign up", new_user_registration_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p><%= @event.description %></p>
<div> List of attendees:
  <% @event.attendee.each do |attendee|%>
  <li><%= attendee.username %></li>
  <%end%>
</div>
<%= link_to "Join event", join_events_path(event_id: @event.id), data: { turbo_method: :post } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Pulse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>